/**
 * Generates src/room/logos.ts — the brand marks used in the Skills drawer.
 *
 * simple-icons is a devDependency only. Importing it at runtime would pull a
 * 3,450-icon index into the bundle for the ~16 marks actually used, so the
 * paths are copied into a small generated module instead.
 *
 * Brands absent from simple-icons are absent on purpose: Adobe, Microsoft,
 * Slack and OpenAI all had their marks removed at the trademark owner's
 * request. Those tools keep a text-only chip rather than having their logo
 * sourced from somewhere less scrupulous.
 *
 *   node scripts/make-logos.mjs
 */
import { writeFileSync } from 'node:fs';
import * as si from 'simple-icons';

/** chip label in content.ts -> simple-icons title */
const MAP = {
  JIRA: 'Jira',
  ClickUp: 'ClickUp',
  Notion: 'Notion',
  Figma: 'Figma',
  Miro: 'Miro',
  Trello: 'Trello',
  Confluence: 'Confluence',
  GitHub: 'GitHub',
  Postman: 'Postman',
  Superset: 'Apache Superset',
  Claude: 'Claude',
  Cursor: 'Cursor',
  Gemini: 'Google Gemini',
  'Google AI Studio': 'Google',
  'GitHub Copilot': 'GitHub Copilot',
  Perplexity: 'Perplexity',
  'DaVinci Resolve': 'DaVinci Resolve',
};

const byTitle = new Map();
for (const key of Object.keys(si)) {
  const icon = si[key];
  if (icon && icon.title) byTitle.set(icon.title.toLowerCase(), icon);
}

const found = {};
const missing = [];
for (const [label, title] of Object.entries(MAP)) {
  const icon = byTitle.get(title.toLowerCase());
  if (!icon) {
    missing.push(`${label} (looked for "${title}")`);
    continue;
  }
  found[label] = { path: icon.path, hex: icon.hex };
}

if (missing.length) {
  throw new Error(
    `make-logos: no icon for:\n  ${missing.join('\n  ')}\n` +
      'Fix the title in MAP or drop the entry — do not source the mark elsewhere.',
  );
}

const body = Object.entries(found)
  .map(([label, { path, hex }]) => `  ${JSON.stringify(label)}: { hex: '${hex}', path: '${path}' },`)
  .join('\n');

writeFileSync(
  'src/room/logos.ts',
  `/**
 * Generated by scripts/make-logos.mjs — do not edit by hand.
 *
 * Brand marks for the tools in the Skills drawer, keyed by the chip label.
 * Anything not listed here renders as a text-only chip, which includes every
 * brand that asked to be removed from simple-icons (Adobe, Microsoft, Slack,
 * OpenAI) and every entry that is a skill rather than a product.
 *
 * The marks are the trademarks of their respective owners and appear here only
 * to identify the tools used.
 */
export type Logo = { hex: string; path: string };

export const LOGOS: Record<string, Logo> = {
${body}
};
`,
);

console.log(`wrote src/room/logos.ts with ${Object.keys(found).length} marks`);
